server:
  port: '9999'

spring:
  main:
    allow-bean-definition-overriding: 'true'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/miru
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  type-aliases-package: com.back.miru.model
  mapper-locations: mapper/**/*.xml

external:
  email:
    username: js97621@gmail.com
    password: fdniriemwghmjapx

logging:
  level:
    com:
      back:
        miru:
          controller: debug
    root: info