server:
  port: 9999

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bank
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/bank
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  type-aliases-package: com.back.bank.model.dto
  mapper-locations: mapper/**/*.xml

jwt:
  token:
    secret: dimple
    expiration: 3600000

#log4jdbc:
#  auto:
#    load:
#      popular:
#        drivers=false
#  spylogdelegator:
#    name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
#  dump:
#    sql:
#      maxlinelength=0
#
## 로그 레벨 : TRACE -> DEBUG -> INFO -> WARN -> ERROR -> FATAL 순서
#logging:
#  level:
#    com:
#      back:
#        bank:
#          hikari: off
#          javax:
#            sql:
#              DataSource: off
#    javax:
#      sql:
#        DataSource: off
#    jdbc:
#      audit: off
#      resultset: off
#      resultsettable: off
#      sqlonly: info
#      sqltiming: off
#    org:
#      hibernate:
#        SQL: off
#        type:
#          descriptor:
#            sql:
#              BasicBinder: off
#    dev:
#      developer:
#        mybatis:
#          mapper: off